# Generated by Django 5.1.2 on 2024-10-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.DecimalField(db_index=True, decimal_places=0, max_digits=10)),
                ('email', models.CharField(max_length=255)),
                ('docType', models.CharField(db_index=True, max_length=2)),
                ('num', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'records',
            },
        ),
    ]
